plugins:
  sidebar_enable:
    default: false
    client: true
  userbar_enabled:
    default: true
    client: true
  my_index:
    default: true
    client: true
  qa_comments_default:
    default: 3
    client: true
